# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 091b3ca3e595612b0e5cde8857aa261081933cd62271457d32eeadcf88b54cfd90203178cbd651e1e509ae1d53f60abc30fd1327db86f346c8f13927678764cc

test:
  secret_key_base: fc331e3d5654a6cdf8615ed860376656fb1b169965c8294ba17f4f579333424afd7f9a77e4c510187f49f3a5b2b63777821d4118d20aba3d39baa394194def34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
